Add draft spec; "alternatives considered" explainer
immersive-web/image-tracking pull request #6
Opened 2021-06-26 23:00 UTC by klausw

Create a draft spec based on the current explainer, and add an "alternatives considered" section to the explainer.

2021-06-28 22:15 UTC, toji requested changes
Looking very good overall! There's some points that I think could be clarified with a bit of additional text or better naming/phrasing.

2021-06-28 22:15 UTC, toji commented on index.bs
> +A [=tracked image=] has a <dfn>image was detected</dfn> flag. This is initially false, and is set to true once the [=suitable for tracking=] algorithm returns true for a frame. This flag indicates th
```suggestion
A [=tracked image=] has an <dfn>image was detected</dfn> flag. This is initially false, and is set to true once the [=suitable for tracking=] algorithm returns true for a frame. This flag indicates that the XR device has found this image during this session and that the UA is going to provide tracking information for it.
```

2021-06-28 22:15 UTC, toji commented on index.bs
> +A [=tracked image=] has an associated <dfn>image tracking score</dfn> which corresponds to the XR device's ability to track this image based on characteristics of the supplied image itself. This is a
The fact that `image tracking score` is a boolean and not a float feels surprising to me. Either we should change the definition to something like "an `image trackable` flag" _or_ we should define it as a float and reword the related "unsuitable for tracking" text to discuss the trackability in terms of thresholds.

Which way we go with that is, in my mind, entirely a matter of what we expect the underlying native APIs to produce by I suspect that keeping it as a boolean and renaming the variable is probably cleaner/more flexible.

2021-06-28 22:15 UTC, toji commented on index.bs
> +  1. If |requested image list| is undefined or an empty list, abort these steps.
Above the text indicates that the `trackedImages` list MUST be set if the feature is requested, but the algorithm doesn't enforce that here. I'm actually OK with allowing an empty list. Seems like that could be useful in some more dynamic scenarios, such as if the tracked image list is being loaded from an external source. (Maybe a compromise is a console warning on an empty or undefined array if we feel like that could be a common developer pitfall.)

Similarly, we don't appear to be checking that the `"marker-tracking"` feature descriptor was set in the algorithm either, and these steps shouldn't execute unless the feature is enabled.

2021-06-28 22:15 UTC, toji commented on index.bs
> +        1. Set |image|'s [=image tracking score=] to either "trackable" or "untrackable" depending on the platform's expected ability to track this image.
Related to an above concern: This variable is defined above as a boolean, but treated here as an enum (with a name that suggests a number). Any of these approaches could be valid, we should just normalize on one of them.

2021-06-28 22:15 UTC, toji commented on index.bs
> +A [=tracked image=] has an associated {{XRImageTrackingState}} <dfn>image tracking state</dfn>. This is null if the image is not being tracked at all, "tracked" if it is actively being tracked and vi
Since we're treating this an an enum it seems cleaner to have an explicit `"untracked"` state rather than allowing the value to be nullable.

2021-06-28 22:15 UTC, toji commented on index.bs
> +        1. Set |image|'s [=image tracking state=] to null.
If the suggestion above is accepted, this should also change from `null` to `"untrackable"`.

2021-06-28 22:15 UTC, toji commented on index.bs
> +enum XRImageTrackingScore {
Okay, I see how this is being used now. An enum does seem appropriate here, but the name is still a potential point of confusion for me. I don't have a great alternative off the top of my head, unfortunately. Perhaps something like:
  - `XRImageTrackability`
  - `XRImageTrackableState`
  - `XRTrackedImageQuality`

2021-06-28 22:15 UTC, toji commented on index.bs
> +  Promise&lt;FrozenArray&lt;XRImageTrackingScore&gt;&gt; getTrackedImageScores();
Obviously if the enum name changes this should be updated too for consistency.

2021-06-28 22:15 UTC, toji commented on index.bs
> +In order to <dfn>obtain image tracking scores</dfn> for an {{XRSession}} |session|, the user agent MUST run the following steps:
...as should anything else that uses the term "score"

2021-06-28 22:15 UTC, toji commented on index.bs
> +  readonly attribute XRImageTrackingState trackingState;
To match the current internal definition this would need to be nullable, but that's a moot point if you make an "untracked" state instead.

2021-06-28 22:15 UTC, toji commented on index.bs
> +NOTE: For example, a hostile application might try to detect large-domination bank notes or other valuable items, specific book covers of titles that may be banned or restricted in certain jurisdicti
```suggestion
NOTE: For example, a hostile application might try to detect large-denomination bank notes or other valuable items, specific book covers of titles that may be banned or restricted in certain jurisdictions, or other information that the user may be unwilling to share.
```

2021-06-28 22:15 UTC, toji commented on index.bs
> +The UA MUST NOT report any tracking information for distant or small images, or images that only appear in peripheral vision.
This section is a little confusing because my assumption is that it intends to primarily limit the _initial_ tracking of an image, after which continuous pose data should be OK even if the image is relatively far from the camera or at the periphery of the field of view. (Otherwise the perceived quality of the API's results would be fairly poor.)

The way this sentence, and others in this section, are worded however makes it feel ambiguous whether it's placing limitations on _initial_ tracking or _ongoing_ tracking. Rephrasing to something like: "The UA MUST NOT initiate tracking for distant or small images, ..." would help. Additionally, adding a paragraph that explains that ones an image has initiated tracking it no longer needs to adhere to these criteria to deliver ongoing tracking information  would reduce the ambiguity.

2021-06-28 22:15 UTC, toji commented on index.bs
> +The following individuals have contributed to the design of the WebXR DOM Overlay specification:
```suggestion
The following individuals have contributed to the design of the WebXR Marker Tracking specification:
```

2021-06-28 22:15 UTC, toji commented on index.bs
> +  * <a href="mailto:nhw@amazon.com">Nell Waliczek</a> (Amazon [Microsoft until 2018])
Copy/paste error? (Unless Nell offered some advice on this a couple of years back that I've since forgotten, which is entirely plausible.)

2021-06-29 01:35 UTC, klausw commented on index.bs
> +A [=tracked image=] has a <dfn>image was detected</dfn> flag. This is initially false, and is set to true once the [=suitable for tracking=] algorithm returns true for a frame. This flag indicates th
Done

2021-06-29 01:46 UTC, klausw commented on index.bs
> +A [=tracked image=] has an associated <dfn>image tracking score</dfn> which corresponds to the XR device's ability to track this image based on characteristics of the supplied image itself. This is a
Yes, this is a bit tricky. I've renamed the spec attribute to `image trackable`. but after discussions with the group I think the consensus was that it's preferable to keep the API-exposed value as an enum to provide some flexibility for future enhancements, for example later adding "marginal", "ok", or "excellent" trackability. If I remember right, nobody was enthusiastic about a float value, but I don't have strong feelings about this myself.

I added a couple of paragraphs (from the explainer) about the semantics.

2021-06-29 01:54 UTC, klausw commented on index.bs
> +  1. If |requested image list| is undefined or an empty list, abort these steps.
Good point, I've changed the text to accept an empty or missing list, and added a check for the `marker-tracking` feature.

2021-06-29 01:55 UTC, klausw commented on index.bs
> +        1. Set |image|'s [=image tracking score=] to either "trackable" or "untrackable" depending on the platform's expected ability to track this image.
Replaced with "true or false".

2021-06-29 02:07 UTC, klausw commented on index.bs
> +A [=tracked image=] has an associated {{XRImageTrackingState}} <dfn>image tracking state</dfn>. This is null if the image is not being tracked at all, "tracked" if it is actively being tracked and vi
I've updated it to add an "untracked" value to the IDL, with a note that this value won't ever appear in results.

I think there isn't really an alternative to a null XRSpace for `image space`, but I guess that is less confusing than a nullable enum.

2021-06-29 02:08 UTC, klausw commented on index.bs
> +        1. Set |image|'s [=image tracking state=] to null.
done, though it's `untracked` not `untrackable`.

2021-06-29 02:13 UTC, klausw commented on index.bs
> +enum XRImageTrackingScore {
I'm leaning towards `XRImageTrackability`, though the others also seem fine for me. I've replaced this in the spec, but it'll hold off on changing the implementation for now until there's consensus.

2021-06-29 02:17 UTC, klausw commented on index.bs
> +  readonly attribute XRImageTrackingState trackingState;
Changed to "untracked". I'm not sure if I fully get the distinction - I assume it's OK for `imageSpace` to not be explicitly marked nullable in the interface? 

Technically I think it would be more accurate to have a separate specification-only result type that's distinct from the IDL-defined type, but that would be confusing if it's essentially identical apart from nullability for spec-internal values that don't get reported through the API.

2021-06-29 02:17 UTC, klausw commented on index.bs
> +NOTE: For example, a hostile application might try to detect large-domination bank notes or other valuable items, specific book covers of titles that may be banned or restricted in certain jurisdicti
Oops, fixed.

2021-06-29 02:20 UTC, klausw commented on index.bs
> +The UA MUST NOT report any tracking information for distant or small images, or images that only appear in peripheral vision.
Yes, this was confusing. I've reworded to say "MUST NOT initiate tracking", and added a note that reporting poses from that point on is OK even if the image ends up distant or partially occluded.

2021-06-29 02:27 UTC, klausw commented on index.bs
> +  * <a href="mailto:nhw@amazon.com">Nell Waliczek</a> (Amazon [Microsoft until 2018])
Oops, indeed copied from the previous spec. I added Alex Turner instead, though I'll need to add an email address later. (It seems I only have github and IRC communications with him which doesn't show that...)

2021-06-29 02:29 UTC, klausw commented on index.bs
> +The following individuals have contributed to the design of the WebXR DOM Overlay specification:
Fixed

2021-06-29 18:13 UTC, toji commented on index.bs
> +A [=tracked image=] has an associated <dfn>image tracking score</dfn> which corresponds to the XR device's ability to track this image based on characteristics of the supplied image itself. This is a
Bool internally and enum externally sounds fine here. 👍

2021-06-30 02:33 UTC, klausw commented on index.bs
> +A [=tracked image=] has an associated {{XRImageTrackingState}} <dfn>image tracking state</dfn>. This is null if the image is not being tracked at all, "tracked" if it is actively being tracked and vi
I've updated the XRSpace usage, there's no more null value and I've added more details about how it interacts with getPose's algorithm.

2021-06-30 02:33 UTC, klausw commented on index.bs
> +enum XRImageTrackingScore {
I went with XRImageTrackability in the current version.

2021-06-30 02:34 UTC, klausw commented on index.bs
> +In order to <dfn>obtain image tracking scores</dfn> for an {{XRSession}} |session|, the user agent MUST run the following steps:
Fixed remaining "score" references.

2021-06-30 02:34 UTC, klausw commented on index.bs
> +  Promise&lt;FrozenArray&lt;XRImageTrackingScore&gt;&gt; getTrackedImageScores();
Done, using `getImageTrackability()`.

2021-06-30 02:35 UTC, klausw commented on index.bs
> +The UA MUST NOT report any tracking information for distant or small images, or images that only appear in peripheral vision.
I've added a bit more clarification around "suitable for tracking".

2021-06-30 17:40 UTC, toji commented on index.bs
> +     1. If |image|'s [=image tracking state=] is {{XRImageTrackingState/"untracked"}}, abort these steps.
```suggestion
     1. If |image|'s [=image tracking state=] is {{XRImageTrackingState/"untracked"}}, then continue.
```

I believe "abort these steps" here would strictly mean "stop the algorithm and process no further images", not just "abort the nested steps." [continue](https://infra.spec.whatwg.org/#iteration-continue) is probably the right control flow mechanism here.

2021-06-30 17:42 UTC, toji approved these changes
LGTM! Thanks for iterating on this, and feel free to merge after you've taken care of the final nit.

2021-07-02 22:11 UTC, klausw commented on index.bs
> +     1. If |image|'s [=image tracking state=] is {{XRImageTrackingState/"untracked"}}, abort these steps.
Fixed here and for "updated tracked images", using "continue to the next entry" to match the main WebXR spec's usage.

2021-07-02 22:12 UTC, merged